from __future__ import annotations

from typing import Any

from core.utils import write_text


def generate_phase1_report(
    report_path,
    source_summary: dict[str, Any],
    metrics: dict[str, Any],
    quality: dict[str, Any],
    freshness: dict[str, Any],
) -> None:
    """Write the phase 1 report from measured artifacts."""
    metric_rows = "\n".join(
        f"| `{name}` | {metrics.get(name, 'N/A')} |"
        for name in ("samples", "retrieval_hit_rate", "mean_token_f1", "judge_accuracy", "mean_judge_score")
    )
    failed = quality.get("failed_checks", [])
    lines = [
        "# Phase 1 — Baseline report",
        "",
        "## Source and artifacts",
        "",
        f"- Source: {source_summary.get('source', 'Unknown')}",
        f"- Raw records: {source_summary.get('raw_records', 'N/A')}",
        f"- Clean records: {source_summary.get('clean_records', 'N/A')}",
        f"- Indexed documents: {source_summary.get('indexed_documents', 'N/A')}",
        f"- Evaluation questions: {source_summary.get('test_questions', 'N/A')}",
        "",
        "## Evaluation",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        metric_rows,
        "",
        "## Data quality and freshness",
        "",
        f"- Quality gate passed: **{quality.get('success', False)}**",
        f"- Failed checks: {', '.join(failed) if failed else 'none'}",
        f"- Freshness SLA passed: **{freshness.get('is_fresh', False)}**",
        f"- Stale records: {freshness.get('stale_rows', 'N/A')}/{freshness.get('total_rows', 'N/A')}",
        f"- Stale ratio: {freshness.get('stale_ratio', 'N/A')}",
        "",
        "Metrics and checks above are generated by the pipeline from the saved dataset.",
        "",
    ]
    write_text(report_path, "\n".join(lines))


def generate_corruption_report(
    report_path,
    baseline_metrics: dict[str, Any],
    corrupted_metrics: dict[str, Any],
    repaired_metrics: dict[str, Any],
    corrupted_quality: dict[str, Any],
    repaired_quality: dict[str, Any],
    corrupted_freshness: dict[str, Any],
    repaired_freshness: dict[str, Any],
) -> None:
    """TODO(student): viet markdown report so sanh baseline/corrupted/repaired."""
    raise NotImplementedError("Student task: implement corruption comparison report.")
